name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: learnmark/website:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEMO_SERVER_IP }}
          port: ${{ secrets.DEMO_SERVER_PORT }}
          username: ${{ secrets.DEMO_SERVER_USERNAME }}
          password: ${{ secrets.DEMO_SERVER_PASSWORD }}
          script: |
            docker stop learnmark
            docker rm learnmark
            docker image rm learnmark/website:latest
            docker pull learnmark/website:latest
            docker run -d --name learnmark -p 90:80 learnmark/website:latest